### ISSUE TITLE
Try alternative StorageSharedKeyCredential for sending blobs to azure

### ISSUE THREAD

**Issue by aeisenberg** [covid-modeling/model-runner#32]
In 
https://github.com/Azure/azure-sdk-for-js/issues/8950 it was suggested that we use `StorageSharedKeyCredential` to authenticate with blob store. If we try this, then maybe we can turn back on concurrency.

**Comment by miskander** [comment]
@aeisenberg or who ever picks up this ticket the call flow here should be:
- Use managed identity to get the shared storage key
- Create a blob storage client using the shared storage key
- Use only the client that authenticates with storage key for all future API calls

cc/ @devigned

**Comment by aeisenberg** [comment]
There was another comment on the issue that we could just try to stagger our uploads. There is a limit of 5 uploads/second. If we wait 1s between uploads, we might be ok.

**Comment by aeisenberg** [comment]
Ah...and I see it was @devigned who mentioned that.

**Comment by devigned** [comment]
The uploads are not throttled, but rather requesting the JWT from the machine local IMDS service (getting the Manage Identity token).

What seems weird to me is it seems like the client is asking for a token for each request. I don't think that should the case. The client should cache the token and only ask upon first request.

Either way, 429s from the IMDS service should be treated as transient failures.

Happy to help if ya'll need a hand.

**Comment by aeisenberg** [comment]
Closed by https://github.com/Azure/azure-sdk-for-js/issues/8950
